#!/bin/bash

echo "🔑 Getting your Supabase Anon Key"
echo "=================================="
echo ""
echo "Your Supabase project reference: syoygenioemredodiezr"
echo "Your Supabase URL: https://syoygenioemredodiezr.supabase.co"
echo ""
echo "To get your anon key:"
echo ""
echo "1. Go to: https://supabase.com/dashboard/project/syoygenioemredodiezr"
echo "2. Click on 'Settings' in the left sidebar"
echo "3. Click on 'API' in the settings menu"
echo "4. Copy the 'anon public' key (NOT the service_role key!)"
echo "5. It should start with: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
echo ""
echo "Then update your .env file:"
echo "VITE_SUPABASE_ANON_KEY=your_copied_key_here"
echo ""
echo "🔗 Direct link: https://supabase.com/dashboard/project/syoygenioemredodiezr/settings/api"
